In [1]:
from ga4 import GA4Metadata, GA4Report

In [4]:
q_meta = GA4Metadata(property_id="357316354")

In [7]:
metadata = q_meta.return_df()

In [10]:
metadata.loc[metadata.Type == "Metric"].head(20)

,Type,API_Name,UI_Name,Description,Custom_definition,Metric_type
193,Metric,active1DayUsers,1-day active users,The number of distinct active users on your si...,False,TYPE_INTEGER
194,Metric,active28DayUsers,28-day active users,The number of distinct active users on your si...,False,TYPE_INTEGER
195,Metric,active7DayUsers,7-day active users,The number of distinct active users on your si...,False,TYPE_INTEGER
196,Metric,activeUsers,Active users,The number of distinct users who visited your ...,False,TYPE_INTEGER
197,Metric,addToCarts,Add to carts,The number of times users added items to their...,False,TYPE_INTEGER
198,Metric,adUnitExposure,Ad unit exposure,The time that an ad unit was exposed to a user...,False,TYPE_MILLISECONDS
199,Metric,advertiserAdClicks,Ads clicks,Total number of times users have clicked on an...,False,TYPE_INTEGER
200,Metric,advertiserAdCost,Ads cost,The total amount you paid for your ads. Includ...,False,TYPE_CURRENCY
201,Metric,advertiserAdCostPerClick,Ads cost per click,Ads cost per click is ad cost divided by ad cl...,False,TYPE_CURRENCY
202,Metric,advertiserAdCostPerConversion,Cost per conversion,Cost per conversion is ad cost divided by conv...,False,TYPE_CURRENCY
203,Metric,advertiserAdImpressions,Ads impressions,The total number of impressions. Includes impr...,False,TYPE_INTEGER
204,Metric,averagePurchaseRevenue,Average purchase revenue,The average purchase revenue in the transactio...,False,TYPE_CURRENCY
205,Metric,averagePurchaseRevenuePerPayingUser,ARPPU,Average revenue per paying user (ARPPU) is the...,False,TYPE_CURRENCY
206,Metric,averagePurchaseRevenuePerUser,Average purchase revenue per user,The average purchase revenue per active user i...,False,TYPE_CURRENCY
207,Metric,averageRevenuePerUser,ARPU,Average revenue per active user (ARPU). The su...,False,TYPE_CURRENCY
208,Metric,averageSessionDuration,Average session duration,The average duration (in seconds) of users' se...,False,TYPE_SECONDS
209,Metric,bounceRate,Bounce rate,The percentage of sessions that were not engag...,False,TYPE_FLOAT
210,Metric,cartToViewRate,Cart-to-view rate,The number of users who added a product(s) to ...,False,TYPE_FLOAT
211,Metric,checkouts,Checkouts,The number of times users started the checkout...,False,TYPE_INTEGER
212,Metric,cohortActiveUsers,Cohort active users,The number of users in the cohort who are acti...,False,TYPE_INTEGER

In [6]:
q_report = GA4Report(property_id="357316354")

In [11]:
q_report.return_df(dimensions=['dateHour', 'customEvent:cv_link'], metrics=['activeUsers', 'newUsers', 'bounceRate'])

,dateHour,customEvent:cv_link,activeUsers,newUsers,bounceRate
0,2023031018,(not set),2.0,2.0,0.0
1,2023031220,(not set),2.0,0.0,0.5
2,2023031712,,2.0,1.0,1.0
3,2023031020,(not set),1.0,0.0,1.0
4,2023031110,(not set),1.0,0.0,1.0
5,2023031123,(not set),1.0,0.0,0.0
6,2023031218,(not set),1.0,1.0,0.0
7,2023031219,(not set),1.0,1.0,0.0
8,2023031220,https://julienolivier3.github.io/cv/,1.0,0.0,1.0
9,2023031311,(not set),1.0,1.0,0.0
10,2023031318,(not set),1.0,1.0,0.0
11,2023031319,(not set),1.0,0.0,0.0
12,2023031319,https://julienolivier3.github.io/cv/,1.0,0.0,1.0
13,2023031421,(not set),1.0,0.0,1.0
14,2023031513,(not set),1.0,0.0,0.0
15,2023031514,(not set),1.0,0.0,1.0
16,2023031517,(not set),1.0,0.0,0.0
17,2023031518,(not set),1.0,0.0,0.0
18,2023031708,,1.0,0.0,0.0
19,2023031708,https://julienolivier3.github.io/cv/,1.0,0.0,1.0
20,2023031712,https://julienolivier3.github.io/cv/,1.0,0.0,1.0